version: "3.9"

services:
  mysql:
    container_name: pizza-viasoft-db
    image: bitnami/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_USER=docker
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=pizza-viasoft
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  pizza-viasoft:
    container_name: pizza-viasoft-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3333:3333"
    environment:
      - DATABASE_URL=mysql://docker:docker@mysql:3306/pizza-viasoft
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
